// Pre-baked demo data for offline presentation mode.
// Used by Demo Mode button AND as offline fallback if a live scan fails.
// Centered near Tampa, FL — visually rich, realistic numbers.

export const DEMO_CENTER = { lat: 27.9506, lon: -82.4572 };

export const DEMO_ORDINANCE = {
  jurisdiction: "Hillsborough County, FL",
  state: "FL",
  max_tower_height_ft: 199,
  setback_requirement: "1:1 ratio to property line",
  permitted_zones: "Industrial, Commercial, Agricultural",
  conditional_use_required: "Yes for towers >100 ft",
  source: "Hillsborough County Land Development Code §6.11.59",
};

export const DEMO_RESULTS = [
  {
    id: "demo-1",
    site_name: "Sunrise Logistics Parcel",
    owner_name: "Sunrise Logistics LLC",
    parcel_address: "4821 Industrial Blvd, Tampa, FL 33619",
    parcel_id: "U-32-29-20-ZZZ-000001-00000.0",
    parcel_size_acres: 4.7,
    zoning_classification: "I-1 Industrial",
    owner_mailing_address: "PO Box 8821, Tampa, FL 33602",
    latitude: 27.9525,
    longitude: -82.4598,
    fema_risk_factor: "X",
    fema_zone_description: "Area of minimal flood hazard",
    fema_risk_level: "minimal",
    fema_sfha: false,
    phone: "(813) 555-0142",
    email: "leasing@sunriselogistics.com",
    match_score: 94,
    match_reason: "Prime I-1 zoning, no SFHA, fiber on-site, 0.3mi to nearest macro tower.",
    airport_iata: "TPA",
    airport_name: "Tampa International · Tampa, FL",
    airport_distance_miles: 4.2,
    airport_lat: 27.9755,
    airport_lon: -82.5332,
    cell_towers: [
      { operator: "Verizon", type: "Macro", distance_miles: 0.3, lat: 27.9518, lon: -82.4612 },
      { operator: "AT&T", type: "Macro", distance_miles: 0.8, lat: 27.9489, lon: -82.4555 },
    ],
    fiber_providers: [
      { provider_name: "Spectrum Business", technology: "Fiber", max_download_speed: 1000, max_upload_speed: 1000 },
    ],
    has_fiber: true,
    fiber_distance_miles: 0.1,
    power_utility: "Tampa Electric Co (TECO)",
    utility_type: "INVESTOR OWNED",
    utility_holding_company: "Emera Inc.",
    transmission_line_distance_miles: 0.4,
    transmission_line_voltage: "138 kV",
    wetlands_present: false,
    wind_speed_mph: 150,
    wind_mri: "MRI 700",
    wind_risk_level: "high",
    in_hurricane_prone_region: true,
    ground_elevation_ft: 38,
  },
  {
    id: "demo-2",
    site_name: "Coastal Properties Trust",
    owner_name: "Coastal Properties Trust",
    parcel_address: "9120 Bay View Rd, Tampa, FL 33619",
    parcel_id: "U-32-29-20-ZZZ-000002-00000.0",
    parcel_size_acres: 8.2,
    zoning_classification: "C-2 Commercial",
    owner_mailing_address: "1500 Bayshore Blvd, Tampa, FL 33606",
    latitude: 27.9489,
    longitude: -82.4555,
    fema_risk_factor: "AE",
    fema_zone_description: "1% annual chance flood",
    fema_risk_level: "high",
    fema_sfha: true,
    fema_bfe: 12,
    phone: "(813) 555-0198",
    email: "contact@coastaltrust.com",
    match_score: 78,
    match_reason: "Large parcel and good zoning, but partial AE flood zone requires elevated foundation.",
    airport_iata: "TPA",
    airport_name: "Tampa International · Tampa, FL",
    airport_distance_miles: 5.1,
    airport_lat: 27.9755,
    airport_lon: -82.5332,
    cell_towers: [
      { operator: "T-Mobile", type: "Macro", distance_miles: 0.7, lat: 27.9501, lon: -82.4501 },
    ],
    fiber_providers: [
      { provider_name: "Frontier", technology: "Fiber", max_download_speed: 500, max_upload_speed: 500 },
    ],
    has_fiber: true,
    fiber_distance_miles: 0.3,
    power_utility: "Tampa Electric Co (TECO)",
    utility_type: "INVESTOR OWNED",
    transmission_line_distance_miles: 0.9,
    transmission_line_voltage: "69 kV",
    wetlands_present: false,
    wind_speed_mph: 150,
    wind_risk_level: "high",
    in_hurricane_prone_region: true,
    ground_elevation_ft: 14,
  },
  {
    id: "demo-3",
    site_name: "Hernandez Family Tract",
    owner_name: "Hernandez Family LLC",
    parcel_address: "12440 Old Hillsborough Hwy, Tampa, FL 33619",
    parcel_id: "U-32-29-20-ZZZ-000003-00000.0",
    parcel_size_acres: 12.3,
    zoning_classification: "A-1 Agricultural",
    owner_mailing_address: "12440 Old Hillsborough Hwy, Tampa, FL 33619",
    latitude: 27.9551,
    longitude: -82.4521,
    fema_risk_factor: "X",
    fema_zone_description: "Area of minimal flood hazard",
    fema_risk_level: "minimal",
    fema_sfha: false,
    phone: "(813) 555-0167",
    email: null,
    match_score: 71,
    match_reason: "Owner-occupied agricultural parcel — high motivation potential, but conditional use permit required.",
    airport_iata: "TPA",
    airport_name: "Tampa International · Tampa, FL",
    airport_distance_miles: 5.3,
    airport_lat: 27.9755,
    airport_lon: -82.5332,
    cell_towers: [
      { operator: "T-Mobile", type: "Small Cell", distance_miles: 1.1, lat: 27.9612, lon: -82.4488 },
    ],
    fiber_providers: [],
    has_fiber: false,
    power_utility: "Tampa Electric Co (TECO)",
    transmission_line_distance_miles: 0.6,
    transmission_line_voltage: "138 kV",
    wetlands_present: true,
    wetland_proximity: "adjacent",
    wetland_types: ["Freshwater Forested/Shrub Wetland"],
    wind_speed_mph: 150,
    wind_risk_level: "high",
    in_hurricane_prone_region: true,
    ground_elevation_ft: 52,
  },
];