/**
 * syncZoningReportToNotion
 *
 * Creates a Notion page in the user's team workspace containing a generated
 * SiteHawk Zoning + Site Plan + Building Permit report.
 *
 * Strategy for choosing the parent page:
 *   1. If payload.parent_page_id is provided → use it directly.
 *   2. Else, search the workspace for a page titled "SiteHawk Reports" and use it.
 *   3. Else, search for "{STATE}-Zoning" and create the report inside that folder.
 *   4. Else, return an error asking the user to specify a parent.
 *
 * Payload:
 *   {
 *     report: { ...generateZoningPermitReport response... },
 *     candidate: { parcel_address, site_name, zoning_classification, ... },
 *     parent_page_id?: string  // optional override
 *   }
 *
 * Returns: { status, page_id, page_url, parent_used }
 */

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const NOTION_API = 'https://api.notion.com/v1';
const NOTION_VERSION = '2022-06-28';

async function notionReq(path, token, init = {}) {
  const res = await fetch(`${NOTION_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      'Notion-Version': NOTION_VERSION,
      'Content-Type': 'application/json',
      ...(init.headers || {}),
    },
  });
  const text = await res.text();
  let data = null;
  try { data = text ? JSON.parse(text) : null; } catch (_) { data = null; }
  if (!res.ok) {
    const msg = data?.message || text || `HTTP ${res.status}`;
    throw new Error(`Notion ${path} → ${res.status}: ${msg}`);
  }
  return data;
}

// Find a page by exact (normalized) title via workspace search
async function findPageByTitle(token, query, exactMatch) {
  const norm = (s) => (s || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  const target = norm(exactMatch);
  const d = await notionReq('/search', token, {
    method: 'POST',
    body: JSON.stringify({
      query,
      filter: { property: 'object', value: 'page' },
      page_size: 25,
    }),
  });
  for (const r of (d?.results || [])) {
    if (r.object !== 'page') continue;
    const titleProp = r.properties && Object.values(r.properties).find(p => p.type === 'title');
    const title = titleProp?.title?.map(t => t.plain_text).join('') || '';
    if (norm(title) === target || norm(title).startsWith(target)) {
      return { id: r.id, title };
    }
  }
  return null;
}

// Convert a report section { field: { value, source, confidence } } into Notion blocks
function sectionToBlocks(heading, section) {
  const blocks = [{
    object: 'block',
    type: 'heading_2',
    heading_2: { rich_text: [{ type: 'text', text: { content: heading } }] },
  }];
  if (!section || typeof section !== 'object') return blocks;

  const labelize = (k) => k.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  for (const [key, cell] of Object.entries(section)) {
    if (!cell || typeof cell !== 'object') continue;
    const value = String(cell.value ?? '').slice(0, 1900);
    const source = String(cell.source ?? 'none');
    const confidence = String(cell.confidence ?? 'low');
    blocks.push({
      object: 'block',
      type: 'paragraph',
      paragraph: {
        rich_text: [
          { type: 'text', text: { content: `${labelize(key)}: ` }, annotations: { bold: true } },
          { type: 'text', text: { content: value } },
          { type: 'text', text: { content: `  [${source} · ${confidence}]` }, annotations: { italic: true, color: 'gray' } },
        ],
      },
    });
  }
  return blocks;
}

function buildReportBlocks(report, candidate) {
  const blocks = [];

  // Site header
  blocks.push({
    object: 'block',
    type: 'callout',
    callout: {
      icon: { type: 'emoji', emoji: '🦅' },
      rich_text: [
        { type: 'text', text: { content: `${candidate?.site_name || 'SiteHawk Site'} — ${candidate?.parcel_address || ''}` }, annotations: { bold: true } },
      ],
    },
  });

  blocks.push({
    object: 'block',
    type: 'paragraph',
    paragraph: {
      rich_text: [
        { type: 'text', text: { content: `Jurisdiction: ${report?.jurisdiction_resolved || 'Unknown'}` } },
      ],
    },
  });

  blocks.push(...sectionToBlocks('Zoning Overview', report?.zoning_overview));
  blocks.push(...sectionToBlocks('Tower Specifics', report?.tower_specifics));
  blocks.push(...sectionToBlocks('Site Plan', report?.site_plan));
  blocks.push(...sectionToBlocks('Building Permit', report?.building_permit));

  blocks.push({
    object: 'block',
    type: 'paragraph',
    paragraph: {
      rich_text: [
        { type: 'text', text: { content: `Generated by SiteHawk · ${new Date().toISOString()}` }, annotations: { italic: true, color: 'gray' } },
      ],
    },
  });

  return blocks;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { report, candidate, parent_page_id } = await req.json();
    if (!report) return Response.json({ error: 'report is required' }, { status: 400 });

    const conn = await base44.asServiceRole.connectors.getConnection('notion');
    const token = conn?.accessToken;
    if (!token) return Response.json({ error: 'Notion is not connected' }, { status: 400 });

    // 1. Resolve parent page
    let parent = parent_page_id ? { id: parent_page_id, title: '(provided)' } : null;
    if (!parent) parent = await findPageByTitle(token, 'SiteHawk Reports', 'SiteHawk Reports');
    if (!parent && report?.geo?.state_code) {
      parent = await findPageByTitle(token, `${report.geo.state_code}-Zoning`, `${report.geo.state_code}Zoning`);
    }
    if (!parent) {
      return Response.json({
        error: 'No parent Notion page found. Create a page called "SiteHawk Reports" in your team workspace and add this integration to it (••• → Connections → SiteHawk).',
      }, { status: 404 });
    }

    // 2. Build title + blocks
    const dateStr = new Date().toISOString().slice(0, 10);
    const title = `${candidate?.site_name || 'Site'} — ${candidate?.parcel_address || 'Unknown'} (${dateStr})`;
    const children = buildReportBlocks(report, candidate || {});

    // 3. Create the page (Notion limits children to 100 per request)
    const firstBatch = children.slice(0, 100);
    const rest = children.slice(100);

    const created = await notionReq('/pages', token, {
      method: 'POST',
      body: JSON.stringify({
        parent: { page_id: parent.id },
        properties: {
          title: { title: [{ type: 'text', text: { content: title } }] },
        },
        children: firstBatch,
      }),
    });

    // Append remaining blocks in batches of 100
    for (let i = 0; i < rest.length; i += 100) {
      const batch = rest.slice(i, i + 100);
      await notionReq(`/blocks/${created.id}/children`, token, {
        method: 'PATCH',
        body: JSON.stringify({ children: batch }),
      });
    }

    console.log(`Notion sync: user=${user.email} parent="${parent.title}" page=${created.id}`);

    return Response.json({
      status: 'ok',
      page_id: created.id,
      page_url: created.url,
      parent_used: parent.title,
    });
  } catch (error) {
    console.error('syncZoningReportToNotion error:', error?.message || error);
    return Response.json({ error: error?.message || String(error) }, { status: 500 });
  }
});