/**
 * HawkLawDisclaimerBanner — PLACEMENT A.
 * Sticky, unmissable legal disclaimer at the top of /hawklaw.
 * Soft amber bg, 4px amber left border, scale-of-justice icon.
 * "Dismiss for this session" collapses it to a 1-line condensed version
 * (kept in sessionStorage so it stays condensed for the browser session).
 */
import { useState } from "react";
import { Scale } from "lucide-react";

const AMBER_BG = "#FEF3C7";
const AMBER_BORDER = "#F59E0B";
const AMBER_ICON = "#B45309";
const SS_KEY = "hawklaw_disclaimer_condensed";

const FULL_BODY =
  "HawkLaw is an AI-powered legal analysis tool and does not provide legal advice. Information generated by HawkLaw does not constitute an attorney-client relationship or legal counsel. Always consult a qualified, licensed attorney in your jurisdiction before signing, modifying, negotiating, or relying on any lease, contract, or legal document. AI analysis may contain errors, omissions, or outdated information. By using HawkLaw, you acknowledge that you are solely responsible for any legal decisions you make.";

export default function HawkLawDisclaimerBanner() {
  const [condensed, setCondensed] = useState(() => {
    try { return sessionStorage.getItem(SS_KEY) === "1"; } catch { return false; }
  });

  function dismiss() {
    try { sessionStorage.setItem(SS_KEY, "1"); } catch { /* ignore */ }
    setCondensed(true);
  }
  function expand() {
    try { sessionStorage.removeItem(SS_KEY); } catch { /* ignore */ }
    setCondensed(false);
  }

  return (
    <div
      className="sticky top-0 z-30 mb-5"
      style={{ background: AMBER_BG, borderLeft: `4px solid ${AMBER_BORDER}` }}
    >
      <div className="flex items-start gap-3 px-4 py-3">
        <Scale className="w-5 h-5 shrink-0 mt-0.5" style={{ color: AMBER_ICON }} />
        {condensed ? (
          <div className="flex-1 flex items-center justify-between gap-3 flex-wrap">
            <p className="text-sm font-semibold" style={{ color: "#78350F" }}>
              ⚠ HawkLaw is NOT a licensed attorney — AI analysis only, not legal advice.
            </p>
            <button onClick={expand} className="text-xs font-medium underline shrink-0" style={{ color: AMBER_ICON }}>
              Show full disclaimer
            </button>
          </div>
        ) : (
          <div className="flex-1">
            <p className="font-bold text-sm" style={{ color: "#78350F" }}>
              HawkLaw is NOT a licensed attorney
            </p>
            <p className="text-sm mt-1 leading-relaxed" style={{ color: "#713F12" }}>
              {FULL_BODY}
            </p>
            <button onClick={dismiss} className="text-xs font-medium underline mt-1.5" style={{ color: AMBER_ICON }}>
              Dismiss for this session
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export { FULL_BODY as HAWKLAW_DISCLAIMER_FULL };